"""changed event date to string

Revision ID: 6e5f76be7191
Revises: f6ee368c9f68
Create Date: 2024-11-01 12:27:22.756185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5f76be7191'
down_revision = 'f6ee368c9f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(length=20),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
