"""added volunteer relationship

Revision ID: cbae7ad719e0
Revises: 6e5f76be7191
Create Date: 2024-11-01 13:17:15.357432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'cbae7ad719e0'
down_revision = '6e5f76be7191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('volunteer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volunteer', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
