"""Made some User attributes nullable at registration

Revision ID: f6ee368c9f68
Revises: 
Create Date: 2024-10-27 18:29:56.729568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f6ee368c9f68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=False),
    sa.Column('skills', sa.VARCHAR(length=255), nullable=True),
    sa.Column('urgency', sa.VARCHAR(length=10), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.Column('admin', sa.BOOLEAN(), nullable=True),
    sa.Column('fullname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address1', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address2', sa.VARCHAR(length=100), nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), nullable=False),
    sa.Column('state', sa.VARCHAR(length=2), nullable=False),
    sa.Column('zipcode', sa.VARCHAR(length=10), nullable=False),
    sa.Column('skills', sqlite.JSON(), nullable=True),
    sa.Column('preference', sa.VARCHAR(length=255), nullable=True),
    sa.Column('availability', sqlite.JSON(), nullable=True),
    sa.Column('volunteer', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
